# Generated by Django 6.0.1 on 2026-02-11 04:01

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='URL của công việc', max_length=500, unique=True)),
                ('thumbnail', models.URLField(blank=True, help_text='URL ảnh thumbnail', max_length=500, null=True)),
                ('job_title', models.CharField(help_text='Tên công việc', max_length=255)),
                ('company_url', models.URLField(blank=True, help_text='URL công ty', max_length=500, null=True)),
                ('company_name', models.CharField(blank=True, help_text='Tên công ty', max_length=255, null=True)),
                ('province', models.CharField(help_text='Tỉnh/thành phố', max_length=100)),
                ('salary', models.CharField(blank=True, help_text='Mức lương', max_length=100, null=True)),
                ('skills', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Danh sách kỹ năng')),
                ('descriptions', models.JSONField(blank=True, help_text='Mô tả công việc (Map)', null=True)),
                ('job_info', models.JSONField(blank=True, help_text='Thông tin công việc (Map)', null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian thu thập')),
            ],
            options={
                'verbose_name': 'Job Detail',
                'verbose_name_plural': 'Job Details',
                'db_table': 'JobDetail',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Tên đăng nhập', max_length=150, unique=True)),
                ('password', models.CharField(help_text='Mật khẩu đã hash', max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('company', 'Company')], default='user', help_text='Vai trò người dùng', max_length=20)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
            },
        ),
    ]
