# Generated by Django 6.0.3 on 2026-03-12 17:14

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Username của công ty', max_length=150)),
                ('name', models.CharField(help_text='Tên công ty', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email công ty', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Số điện thoại', max_length=20, null=True)),
                ('website', models.URLField(blank=True, help_text='Website công ty', max_length=500, null=True)),
                ('address', models.TextField(blank=True, help_text='Địa chỉ', null=True)),
                ('logo', models.CharField(blank=True, help_text='Link logo', max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả công ty', null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='URL của công việc', max_length=500, unique=True)),
                ('thumbnail', models.URLField(blank=True, help_text='URL ảnh thumbnail', max_length=500, null=True)),
                ('job_title', models.CharField(help_text='Tên công việc', max_length=255)),
                ('company_url', models.URLField(blank=True, help_text='URL công ty', max_length=500, null=True)),
                ('company_name', models.CharField(blank=True, help_text='Tên công ty', max_length=255, null=True)),
                ('province', models.CharField(help_text='Tỉnh/thành phố', max_length=100)),
                ('salary', models.CharField(blank=True, help_text='Mức lương', max_length=100, null=True)),
                ('source', models.CharField(blank=True, help_text='Nguồn website (topcv, devwork, ...)', max_length=50, null=True)),
                ('skills', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Danh sách kỹ năng')),
                ('descriptions', models.JSONField(blank=True, help_text='Mô tả công việc (Map)', null=True)),
                ('job_info', models.JSONField(blank=True, help_text='Thông tin công việc (Map)', null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian thu thập')),
            ],
            options={
                'verbose_name': 'Job Detail',
                'verbose_name_plural': 'Job Details',
                'db_table': 'JobDetail',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(db_index=True, help_text='User ID nhận thông báo', max_length=255)),
                ('JobDetailID', models.CharField(blank=True, db_index=True, help_text='ID của JobDetail', max_length=255, null=True)),
                ('content', models.TextField(help_text='Nội dung thông báo')),
                ('status', models.CharField(choices=[('chưa đọc', 'Chưa đọc'), ('đã đọc', 'Đã đọc')], default='chưa đọc', help_text='Trạng thái thông báo', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'Notification',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('_id', models.CharField(blank=True, db_column='_id', editable=False, max_length=24, primary_key=True, serialize=False)),
                ('urls', models.JSONField(default=list, help_text='Danh sách URLs cần crawl')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Trạng thái job', max_length=20)),
                ('jobCount', models.IntegerField(default=0, help_text='Số lượng jobs đã crawl')),
                ('errorMessage', models.TextField(blank=True, help_text='Thông báo lỗi', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata bổ sung')),
                ('totalUrls', models.IntegerField(default=0, help_text='Tổng số URLs')),
                ('processedUrls', models.IntegerField(default=0, help_text='Số URLs đã xử lý')),
                ('currentUrl', models.CharField(blank=True, help_text='URL đang xử lý', max_length=1000, null=True)),
                ('progress', models.IntegerField(default=0, help_text='Phần trăm hoàn thành (0-100)')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('completedAt', models.DateTimeField(blank=True, help_text='Thời gian hoàn thành', null=True)),
            ],
            options={
                'verbose_name': 'Scrape Job',
                'verbose_name_plural': 'Scrape Jobs',
                'db_table': 'ScrapeJob',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Tên đăng nhập', max_length=150, unique=True)),
                ('password', models.CharField(help_text='Mật khẩu đã hash', max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('company', 'Company')], default='user', help_text='Vai trò người dùng', max_length=20)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(db_index=True, help_text='Username của user', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, help_text='Họ và tên', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Số điện thoại', max_length=20, null=True)),
                ('gender', models.CharField(choices=[('nam', 'Nam'), ('nữ', 'Nữ'), ('other', 'Khác')], default='nam', help_text='Giới tính', max_length=10)),
                ('birthdate', models.DateField(blank=True, help_text='Ngày sinh', null=True)),
                ('cv', models.CharField(blank=True, help_text='Link CV', max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả bản thân', null=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(db_index=True, help_text='Username của người ứng tuyển', max_length=150)),
                ('JobDetailID', models.CharField(db_index=True, help_text='ID của JobDetail', max_length=255)),
                ('status', models.CharField(default='chưa duyệt', help_text='Trạng thái: chưa duyệt, đã duyệt, đã từ chối', max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True, help_text='Thời gian ứng tuyển')),
                ('content', models.TextField(blank=True, help_text='Nội dung thông báo từ công ty', null=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'Application',
                'unique_together': {('userID', 'JobDetailID')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(db_index=True, help_text='Username của người dùng', max_length=150)),
                ('JobDetailID', models.CharField(db_index=True, help_text='ID của JobDetail', max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True, help_text='Thời gian lưu')),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
                'db_table': 'Follow',
                'unique_together': {('userID', 'JobDetailID')},
            },
        ),
    ]
