# Generated by Django 6.0.3 on 2026-03-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_application_id_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='source',
            field=models.CharField(blank=True, help_text='Nguồn của job (domain)', max_length=100, null=True),
        ),
    ]
