# Generated by Django 6.0.3 on 2026-04-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_deadline'),
        ('api', '0003_alter_application_id_alter_company_id_and_more'),
    ]

    operations = [
    ]
