# Generated by Django 6.0.3 on 2026-04-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20260406_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='JobDetailID',
            field=models.CharField(db_column='jobId', db_index=True, help_text='ID của JobDetail', max_length=255),
        ),
        migrations.AlterField(
            model_name='follow',
            name='userID',
            field=models.CharField(db_column='userId', db_index=True, help_text='Username của người dùng', max_length=150),
        ),
    ]
