# Generated by ChatGPT on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_follow_jobdetailid_alter_follow_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='lastError',
            field=models.TextField(blank=True, help_text='Loi gan nhat', null=True),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='retryCount',
            field=models.IntegerField(default=0, help_text='So lan retry'),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='maxRetries',
            field=models.IntegerField(default=3, help_text='Gioi han retry'),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='retryDelay',
            field=models.IntegerField(default=30, help_text='Delay retry (giay)'),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='lastAttemptAt',
            field=models.DateTimeField(blank=True, help_text='Lan chay gan nhat', null=True),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='nextRetryAt',
            field=models.DateTimeField(blank=True, help_text='Thoi gian retry tiep theo', null=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('queued', 'Queued'),
                    ('processing', 'Processing'),
                    ('retrying', 'Retrying'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                ],
                default='pending',
                help_text='Trang thai job',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='ScrapeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Ten lich (tuy chon)', max_length=200, null=True)),
                ('urls', models.JSONField(default=list, help_text='Danh sach URLs can crawl')),
                ('scheduleType', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('cron', 'Cron')], default='weekly', help_text='Loai lich chay', max_length=20)),
                ('dayOfWeek', models.IntegerField(blank=True, help_text='Thu trong tuan (0=Mon, 6=Sun)', null=True)),
                ('timeOfDay', models.CharField(default='09:00', help_text='Gio chay (HH:MM)', max_length=5)),
                ('cronExpression', models.CharField(blank=True, help_text='Cron expression neu dung lich cron', max_length=100, null=True)),
                ('active', models.BooleanField(default=True, help_text='Bat/tat lich')),
                ('lastRunAt', models.DateTimeField(blank=True, help_text='Lan chay gan nhat', null=True)),
                ('nextRunAt', models.DateTimeField(blank=True, help_text='Lan chay tiep theo', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Thoi gian tao')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Thoi gian cap nhat')),
            ],
            options={
                'verbose_name': 'Scrape Schedule',
                'verbose_name_plural': 'Scrape Schedules',
                'db_table': 'ScrapeSchedule',
                'ordering': ['-createdAt'],
            },
        ),
    ]
