# Generated by Django 6.0.3 on 2026-06-02 03:16

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_scrape_queue_and_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='url_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash của URL đã chuẩn hóa để chống duplicate', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scrapeschedule',
            name='crawlMode',
            field=models.CharField(choices=[('detail_urls', 'Detail URLs'), ('crawl_then_scrape', 'Crawl then Scrape')], default='detail_urls', help_text='Chế độ crawl: detail_urls (scrape trực tiếp) hoặc crawl_then_scrape (crawl list rồi scrape detail)', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapeschedule',
            name='maxDetailUrls',
            field=models.IntegerField(blank=True, help_text='Giới hạn số lượng detail URL khi crawl_then_scrape', null=True),
        ),
        migrations.AddField(
            model_name='scrapeschedule',
            name='source',
            field=models.CharField(default='manual', help_text='Nguồn crawl (itworks, devwork, topcv, manual)', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='deadline',
            field=models.DateField(blank=True, db_index=True, help_text='Ngày hết hạn nộp hồ sơ', null=True),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='url',
            field=models.URLField(db_index=True, help_text='URL gốc/canonical của công việc', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='lastAttemptAt',
            field=models.DateTimeField(blank=True, help_text='Lần chạy gần nhất', null=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='lastError',
            field=models.TextField(blank=True, help_text='Lỗi gần nhất', null=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='maxRetries',
            field=models.IntegerField(default=3, help_text='Giới hạn retry'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='nextRetryAt',
            field=models.DateTimeField(blank=True, help_text='Thời gian retry tiếp theo', null=True),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='retryCount',
            field=models.IntegerField(default=0, help_text='Số lần retry'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='retryDelay',
            field=models.IntegerField(default=30, help_text='Delay retry (giây)'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('retrying', 'Retrying'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Trạng thái job', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapeschedule',
            name='active',
            field=models.BooleanField(default=True, help_text='Bật/tắt lịch'),
        ),
        migrations.AlterField(
            model_name='scrapeschedule',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='scrapeschedule',
            name='cronExpression',
            field=models.CharField(blank=True, help_text='Cron expression nếu dùng lịch cron', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeschedule',
            name='dayOfWeek',
            field=models.IntegerField(blank=True, help_text='Thứ trong tuần (0=Mon, 6=Sun)', null=True),
        ),
        migrations.AlterField(
            model_name='scrapeschedule',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scrapeschedule',
            name='lastRunAt',
            field=models.DateTimeField(blank=True, help_text='Lần chạy gần nhất', null=True),
        ),
        migrations.AlterField(
            model_name='scrapeschedule',
            name='name',
            field=models.CharField(blank=True, help_text='Tên lịch (tùy chọn)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeschedule',
            name='nextRunAt',
            field=models.DateTimeField(blank=True, help_text='Lần chạy tiếp theo', null=True),
        ),
        migrations.AlterField(
            model_name='scrapeschedule',
            name='scheduleType',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('cron', 'Cron')], default='weekly', help_text='Loại lịch chạy', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapeschedule',
            name='timeOfDay',
            field=models.CharField(default='09:00', help_text='Giờ chạy (HH:MM)', max_length=5),
        ),
        migrations.AlterField(
            model_name='scrapeschedule',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật'),
        ),
        migrations.AlterField(
            model_name='scrapeschedule',
            name='urls',
            field=models.JSONField(default=list, help_text='Danh sách URLs cần crawl'),
        ),
    ]
